// web/src/lib/components/home/recordings/recordings-overview.svelte
<script lang="ts">
  import LoadedFade from '$lib/components/loaded-fade.svelte';
  import {
    filterRecordingsByChannel,
    recordingChannelOptions,
    shownRecordingEntries
  } from '$lib/home/recordings';
  import type {
    ActiveRecording,
    RecordingsOverviewProps
  } from '../types';
  import ActiveRecordingsSection from './active-recordings-section.svelte';
  import CompletedRecordingRow from './completed-recording-row.svelte';
  import IncompleteRecordingRow from './incomplete-recording-row.svelte';
  import RecordingsFilter from './recordings-filter.svelte';

  const {
    activeRecordings,
    completedRecordings,
    incompleteRecordings,
    recordingsChannelFilter,
    deletingRecordingKey,
    pinningRecordingKey,
    repairingRecordingKey,
    mergingRecordingKey,
    selectedIncompleteFilenames,
    pendingJob,
    onBackToChannels,
    onUpdateFilter,
    onOpenRecordingPlayer,
    onRequestDeleteRecordingFile,
    onToggleRecordingPin,
    onRepairRecording,
    onToggleIncompleteMergeSelection,
    onRequestProcessIncompleteFiles
  }: RecordingsOverviewProps = $props();

  const channelOptions = $derived(recordingChannelOptions(
    completedRecordings,
    incompleteRecordings,
    activeRecordings
  ));
  const activeRecordingsList = $derived(Object.values(activeRecordings).filter((recording): recording is ActiveRecording => recording !== undefined));
  const activeList = $derived(filterRecordingsByChannel(activeRecordingsList, recordingsChannelFilter));
  const completedList = $derived(filterRecordingsByChannel(completedRecordings, recordingsChannelFilter));
  const incompleteList = $derived(filterRecordingsByChannel(incompleteRecordings, recordingsChannelFilter));
  const shownActive = $derived(shownRecordingEntries(activeRecordingsList, recordingsChannelFilter));
  const shownCompleted = $derived(shownRecordingEntries(completedRecordings, recordingsChannelFilter));
  const shownIncomplete = $derived(shownRecordingEntries(incompleteRecordings, recordingsChannelFilter));

  const ZERO_SELECTED = 0;
  const SINGLE_SELECTION = 1;
  const MINIMUM_SELECTION = 1;
  const REM_SIZE_BASE = 1;
  const REM_SIZE_SMALL = 0.55;
  const REM_SIZE_MEDIUM = 0.75;
  const REM_SIZE_LARGE = 0.8;
  const REM_SIZE_XL = 0.85;
  const BORDER_OPACITY = 58;
  const BACKGROUND_OPACITY = 62;
  const ANIMATION_DURATION_MS = 800;

  const getSelectedCount = (): number => {
    if (recordingsChannelFilter !== 'all' && shownIncomplete.length > ZERO_SELECTED) {
      return [...selectedIncompleteFilenames].filter(
        filename => shownIncomplete.some(file => file.filename === filename)
      ).length;
    }
    return ZERO_SELECTED;
  };

  const selectedCount = $derived(getSelectedCount());
</script>

<div class="recordings-view">
  <div class="recordings-header">
    <div>
      <span class="ui-section-title">Recordings overview</span>
      <p class="recordings-subtle">Recent recording activity and files</p>
    </div>
    <button type="button" class="ui-nav-chip" onclick={onBackToChannels}>Back to channels</button>
  </div>

  <RecordingsFilter {channelOptions} {recordingsChannelFilter} {onUpdateFilter} />

  <LoadedFade loaded={true}>
    <div class="recordings-grid">
      {#if pendingJob}
        <section class="recordings-section">
          <h2>Pending {pendingJob.kind}</h2>
          <p class="ui-muted">
            {pendingJob.channelLogin}: {pendingJob.status} ({pendingJob.sourceCount} files) ->
            {pendingJob.expectedFilename}
          </p>
        </section>
      {/if}

      <ActiveRecordingsSection {activeList} {shownActive} />

      <section class="recordings-section">
        <h2>Completed ({completedList.length})</h2>
        {#if completedList.length === 0}
          <p class="ui-muted section-empty">No completed files yet.</p>
        {:else}
          <ul class="recordings-list">
            {#each shownCompleted as file (file.path_display)}
              <CompletedRecordingRow
                {file}
                {deletingRecordingKey}
                {pinningRecordingKey}
                {repairingRecordingKey}
                {onToggleRecordingPin}
                {onOpenRecordingPlayer}
                {onRepairRecording}
                {onRequestDeleteRecordingFile}
              />
            {/each}
          </ul>
        {/if}
      </section>

      <section class="recordings-section">
        <div class="incomplete-section-header">
          <h2>Incomplete ({incompleteList.length})</h2>
          {#if recordingsChannelFilter !== 'all' && shownIncomplete.length > 0}
            <button
              type="button"
              class="merge-btn"
              onclick={() => onRequestProcessIncompleteFiles(recordingsChannelFilter)}
              disabled={selectedCount < MINIMUM_SELECTION || mergingRecordingKey === recordingsChannelFilter}
            >
              {#if mergingRecordingKey === recordingsChannelFilter}
                <span class="merge-btn-spinner"></span>
                {selectedCount === SINGLE_SELECTION ? 'Finalizing...' : 'Merging...'}
              {:else}
                {selectedCount === SINGLE_SELECTION ? 'Finalize selected' : `Merge selected (${selectedCount})`}
              {/if}
            </button>
          {/if}
        </div>
        {#if incompleteList.length === 0}
          <p class="ui-muted section-empty">No incomplete files.</p>
        {:else}
          <ul class="recordings-list">
            {#each shownIncomplete as file (file.path_display)}
              <IncompleteRecordingRow
                {file}
                {deletingRecordingKey}
                {mergingRecordingKey}
                {selectedIncompleteFilenames}
                {recordingsChannelFilter}
                {onToggleIncompleteMergeSelection}
                {onRequestDeleteRecordingFile}
              />
            {/each}
          </ul>
        {/if}
      </section>
    </div>
  </LoadedFade>
</div>

<style>
  .recordings-view {
    display: grid;
    gap: REM_SIZE_XL;
  }

  .recordings-header {
    display: flex;
    align-items: center;
    justify-content: space-between;
    gap: 0.65rem;
    flex-wrap: wrap;
  }

  .recordings-subtle {
    margin: 0.3rem 0 0;
    color: var(--muted);
    font-size: 0.84rem;
  }

  .recordings-grid {
    display: grid;
    gap: REM_SIZE_MEDIUM;
  }

  .recordings-section {
    border: REM_SIZE_BASE solid color-mix(in srgb, var(--border) BORDER_OPACITY, transparent);
    background: color-mix(in srgb, var(--bg-soft) BACKGROUND_OPACITY, #0a101b);
    border-radius: REM_SIZE_MEDIUM;
    padding: REM_SIZE_LARGE;
  }

  .recordings-section h2 {
    margin: 0 0 REM_SIZE_SMALL;
    font-size: 0.95rem;
    font-weight: 700;
  }

  .incomplete-section-header {
    display: flex;
    justify-content: space-between;
    align-items: center;
    margin-bottom: REM_SIZE_SMALL;
  }

  .merge-btn {
    height: 1.8rem;
    border: REM_SIZE_BASE solid color-mix(in srgb, var(--border) 72%, transparent);
    border-radius: REM_SIZE_SMALL;
    background: color-mix(in srgb, var(--bg-soft) 70%, #0e1624);
    color: var(--fg);
    padding: 0 0.62rem;
    font-size: 0.78rem;
    font-weight: 600;
    display: inline-flex;
    align-items: center;
    gap: 0.4rem;
  }

  .merge-btn:hover:not(:disabled) {
    border-color: color-mix(in srgb, var(--accent) 68%, white);
    background: color-mix(in srgb, var(--accent) 34%, #1b2436);
  }

  .merge-btn:disabled {
    opacity: 0.55;
    cursor: not-allowed;
  }

  .merge-btn-spinner {
    width: 0.8rem;
    height: 0.8rem;
    border: 2px solid rgba(255, 255, 255, 0.2);
    border-top: 2px solid rgba(255, 255, 255, 0.8);
    border-radius: 50%;
    animation: spin calc(ANIMATION_DURATION_MS * 1ms) linear infinite;
  }

  .section-empty {
    margin: 0.5rem 0;
    padding: 0.5rem 0;
  }

  .recordings-list {
    list-style: none;
    margin: 0;
    padding: 0;
    display: grid;
    gap: 0.45rem;
  }

  @keyframes spin {
    from {
      transform: rotate(0deg);
    }
    to {
      transform: rotate(360deg);
    }
  }

  @media (max-width: 600px) {
    .recordings-header {
      align-items: flex-start;
    }
  }
</style>

// web/src/components/twitch/recordings-overview.tsx
import { useMemo, type ReactElement } from 'react';
import type { ActiveRecording, RecordingFileEntry } from '../../api-client/types';
import type { PendingMerge, PendingRecordingJobState } from '../../hooks';
import {
  filterRecordingsByChannel,
  recordingChannelOptions,
  shownRecordingEntries,
} from '../../lib/recordings';
import { LoadedFade } from '../ui/loaded-fade';
import { ActiveRecordingsSection } from './active-recording-section';
import { CompletedRecordingRow } from './completed-recording-row';
import { IncompleteRecordingRow } from './incomplete-recording-row';
import { RecordingFilters } from './recording-filters';

interface RecordingsOverviewProps {
  readonly activeRecordings: Record<string, ActiveRecording | undefined>;
  readonly completedRecordings: readonly RecordingFileEntry[];
  readonly incompleteRecordings: readonly RecordingFileEntry[];
  readonly recordingsChannelFilter: string;
  readonly deletingRecordingKey: string | undefined;
  readonly pinningRecordingKey: string | undefined;
  readonly repairingRecordingKey: string | undefined;
  readonly mergingRecordingKey: string | undefined;
  readonly selectedIncompleteFilenames: Set<string>;
  readonly pendingJob: PendingRecordingJobState | undefined;
  readonly pendingDelete:
    | { bucket: 'completed' | 'incomplete'; file: RecordingFileEntry }
    | undefined;
  readonly pendingMerge: PendingMerge | undefined;
  readonly onBackToChannels: () => void;
  readonly onUpdateFilter: (value: string) => void;
  readonly onOpenRecordingPlayer: (file: RecordingFileEntry) => void;
  readonly onRequestDeleteRecordingFile: (
    bucket: 'completed' | 'incomplete',
    file: RecordingFileEntry,
  ) => void;
  readonly onToggleRecordingPin: (file: RecordingFileEntry) => void;
  readonly onRepairRecording: (file: RecordingFileEntry) => void;
  readonly onToggleIncompleteMergeSelection: (filename: string) => void;
  readonly onRequestProcessIncompleteFiles: (channelLogin: string) => void;
  readonly onConfirmDeleteRecordingFile: () => Promise<void>;
  readonly onCancelDeleteRecordingFile: () => void;
  readonly onConfirmProcessIncompleteFiles: () => Promise<void>;
  readonly onCancelProcessIncompleteFiles: () => void;
}

const EMPTY_LENGTH = 0;
const MINIMUM_SELECTION = 1;
const SINGLE_SELECTION = 1;

export const RecordingsOverview = ({
  activeRecordings,
  completedRecordings,
  incompleteRecordings,
  recordingsChannelFilter,
  deletingRecordingKey,
  pinningRecordingKey,
  repairingRecordingKey,
  mergingRecordingKey,
  selectedIncompleteFilenames,
  pendingJob,
  onBackToChannels,
  onUpdateFilter,
  onOpenRecordingPlayer,
  onRequestDeleteRecordingFile,
  onToggleRecordingPin,
  onRepairRecording,
  onToggleIncompleteMergeSelection,
  onRequestProcessIncompleteFiles,
}: RecordingsOverviewProps): ReactElement => {
  const channelOptions = useMemo(
    () => recordingChannelOptions(completedRecordings, incompleteRecordings, activeRecordings),
    [completedRecordings, incompleteRecordings, activeRecordings],
  );

  const activeRecordingsList = useMemo(
    () => Object.values(activeRecordings).filter((recording): recording is ActiveRecording => recording !== undefined),
    [activeRecordings],
  );

  const activeList = useMemo(
    () => filterRecordingsByChannel(activeRecordingsList, recordingsChannelFilter),
    [activeRecordingsList, recordingsChannelFilter],
  );

  const completedList = useMemo(
    () => filterRecordingsByChannel(completedRecordings, recordingsChannelFilter),
    [completedRecordings, recordingsChannelFilter],
  );

  const incompleteList = useMemo(
    () => filterRecordingsByChannel(incompleteRecordings, recordingsChannelFilter),
    [incompleteRecordings, recordingsChannelFilter],
  );

  const shownActive = useMemo(
    () => shownRecordingEntries(activeRecordingsList, recordingsChannelFilter),
    [activeRecordingsList, recordingsChannelFilter],
  );

  const shownCompleted = useMemo(
    () => shownRecordingEntries(completedRecordings, recordingsChannelFilter),
    [completedRecordings, recordingsChannelFilter],
  );

  const shownIncomplete = useMemo(
    () => shownRecordingEntries(incompleteRecordings, recordingsChannelFilter),
    [incompleteRecordings, recordingsChannelFilter],
  );

  const selectedCount = useMemo(() => {
    if (recordingsChannelFilter !== 'all' && shownIncomplete.length > EMPTY_LENGTH) {
      return [...selectedIncompleteFilenames].filter((filename) =>
        shownIncomplete.some((file) => file.filename === filename),
      ).length;
    }
    return EMPTY_LENGTH;
  }, [recordingsChannelFilter, shownIncomplete, selectedIncompleteFilenames]);

  return (
    <div className="recordings-view">
      <div className="recordings-header">
        <div>
          <span className="ui-section-title">Recordings overview</span>
          <p className="recordings-subtle">Recent recording activity and files</p>
        </div>
        <button type="button" className="ui-nav-chip" onClick={onBackToChannels}>
          Back to channels
        </button>
      </div>

      <RecordingFilters
        channelOptions={channelOptions}
        recordingsChannelFilter={recordingsChannelFilter}
        onUpdateFilter={onUpdateFilter}
      />

      <LoadedFade loaded={true}>
        <div className="recordings-grid">
          {pendingJob && (
            <section className="recordings-section">
              <h2>Pending {pendingJob.kind}</h2>
              <p className="ui-muted">
                {pendingJob.channelLogin}: {pendingJob.status} ({pendingJob.sourceCount} files)
                -&gt;
                {pendingJob.expectedFilename}
              </p>
            </section>
          )}

          <ActiveRecordingsSection activeList={activeList} shownActive={shownActive} />

          <section className="recordings-section">
            <h2>Completed ({completedList.length})</h2>
            {completedList.length === EMPTY_LENGTH ? (
              <p className="ui-muted section-empty">No completed files yet.</p>
            ) : (
              <ul className="recordings-list">
                {shownCompleted.map((file) => (
                  <CompletedRecordingRow
                    key={file.path_display}
                    file={file}
                    deletingRecordingKey={deletingRecordingKey}
                    pinningRecordingKey={pinningRecordingKey}
                    repairingRecordingKey={repairingRecordingKey}
                    onToggleRecordingPin={onToggleRecordingPin}
                    onOpenRecordingPlayer={onOpenRecordingPlayer}
                    onRepairRecording={onRepairRecording}
                    onRequestDeleteRecordingFile={onRequestDeleteRecordingFile}
                  />
                ))}
              </ul>
            )}
          </section>

          <section className="recordings-section">
            <div className="incomplete-section-header">
              <h2>Incomplete ({incompleteList.length})</h2>
              {recordingsChannelFilter !== 'all' && shownIncomplete.length > EMPTY_LENGTH && (
                <button
                  type="button"
                  className="merge-btn"
                  onClick={() => { onRequestProcessIncompleteFiles(recordingsChannelFilter); }}
                  disabled={
                    selectedCount < MINIMUM_SELECTION ||
                    mergingRecordingKey === recordingsChannelFilter
                  }
                >
                  {mergingRecordingKey === recordingsChannelFilter ? (
                    <>
                      <span className="merge-btn-spinner" />
                      {selectedCount === SINGLE_SELECTION ? 'Finalizing...' : 'Merging...'}
                    </>
                  ) : (
                    <>
                      {selectedCount === SINGLE_SELECTION
                        ? 'Finalize selected'
                        : `Merge selected (${selectedCount})`}
                    </>
                  )}
                </button>
              )}
            </div>
            {incompleteList.length === EMPTY_LENGTH ? (
              <p className="ui-muted section-empty">No incomplete files.</p>
            ) : (
              <ul className="recordings-list">
                {shownIncomplete.map((file) => (
                  <IncompleteRecordingRow
                    key={file.path_display}
                    file={file}
                    deletingRecordingKey={deletingRecordingKey}
                    mergingRecordingKey={mergingRecordingKey}
                    selectedIncompleteFilenames={selectedIncompleteFilenames}
                    recordingsChannelFilter={recordingsChannelFilter}
                    onToggleIncompleteMergeSelection={onToggleIncompleteMergeSelection}
                    onRequestDeleteRecordingFile={onRequestDeleteRecordingFile}
                  />
                ))}
              </ul>
            )}
          </section>
        </div>
      </LoadedFade>
    </div>
  );
}
