// web/src/lib/components/ui/confirm-dialog.svelte
<script lang="ts">
  import type { Snippet } from 'svelte';

  interface Props {
    cancelText?: string;
    children: Snippet;
    confirmText: string;
    confirmVariant?: 'primary' | 'danger';
    initialFocus?: 'confirm' | 'cancel';
    isBusy: boolean;
    isOpen: boolean;
    onCancel: () => void;
    onConfirm: () => void;
  }

  const {
    cancelText = 'Cancel',
    children,
    confirmText,
    confirmVariant = 'primary',
    initialFocus = 'cancel',
    isBusy,
    isOpen,
    onCancel,
    onConfirm,
  }: Props = $props();

  const FOCUS_TIMEOUT_MS = 0;
  const FIRST_ELEMENT_INDEX = 0;
  const LAST_ELEMENT_OFFSET = 1;
  const TRANSITION_DURATION_MS = 180;

  let isExiting = $state(false);
  let modalElement = $state<HTMLDivElement | undefined>();
  let confirmButton = $state<HTMLButtonElement | undefined>();
  let cancelButton = $state<HTMLButtonElement | undefined>();
  let lastFocusedElement = $state<HTMLElement | undefined>();

  $effect(() => {
    if (isOpen) {
      isExiting = false;
      // Store the element that had focus before opening
      lastFocusedElement = document.activeElement as HTMLElement | undefined;
    }
  });

  $effect(() => {
    if (isOpen && !isExiting && modalElement) {
      // Focus the initial element after the modal is rendered
      setTimeout(() => {
        if (initialFocus === 'confirm' && confirmButton) {
          confirmButton.focus({ preventScroll: true });
        } else if (cancelButton) {
          cancelButton.focus({ preventScroll: true });
        }
      }, FOCUS_TIMEOUT_MS);
    }
  });

  const restoreFocus = (): void => {
    if (lastFocusedElement !== undefined && typeof lastFocusedElement.focus === 'function') {
      lastFocusedElement.focus({ preventScroll: true });
    }
  };

  const handleCancel = (): void => {
    if (isBusy) {
      return;
    }
    isExiting = true;
    setTimeout(() => {
      onCancel();
      restoreFocus();
    }, TRANSITION_DURATION_MS);
  };

  const handleConfirm = (): void => {
    if (isBusy) {
      return;
    }
    onConfirm();
  };

  const handleOverlayClick = (): void => {
    if (!isBusy) {
      handleCancel();
    }
  };

  const handleEscape = (event: KeyboardEvent): boolean => {
    if (event.key === 'Escape' && !isBusy) {
      event.preventDefault();
      handleCancel();
      return true;
    }
    return false;
  };

  const getFocusableElements = (): NodeListOf<Element> | null => {
    if (!modalElement) {
      return null;
    }
    return modalElement.querySelectorAll(
      'button, [href], input, select, textarea, [tabindex]:not([tabindex="-1"])'
    );
  };

  const focusLastElement = (lastElement: HTMLElement): void => {
    lastElement.focus({ preventScroll: true });
  };

  const focusFirstElement = (firstElement: HTMLElement): void => {
    firstElement.focus({ preventScroll: true });
  };

  const handleShiftTab = (event: KeyboardEvent, firstElement: HTMLElement, lastElement: HTMLElement): void => {
    // Shift+Tab: if on first element, wrap to last
    if (document.activeElement === firstElement) {
      event.preventDefault();
      focusLastElement(lastElement);
    }
  };

  const handleTab = (event: KeyboardEvent, firstElement: HTMLElement, lastElement: HTMLElement): void => {
    // Tab: if on last element, wrap to first
    if (document.activeElement === lastElement) {
      event.preventDefault();
      focusFirstElement(firstElement);
    }
  };

  const handleTabNavigation = (event: KeyboardEvent): void => {
    const focusableElements = getFocusableElements();
    if (!focusableElements) {
      return;
    }
    const firstElement = focusableElements[FIRST_ELEMENT_INDEX] as HTMLElement;
    const lastElement = focusableElements[focusableElements.length - LAST_ELEMENT_OFFSET] as HTMLElement;

    if (event.shiftKey) {
      handleShiftTab(event, firstElement, lastElement);
    } else {
      handleTab(event, firstElement, lastElement);
    }
  };

  const handleKeydown = (event: KeyboardEvent): void => {
    if (handleEscape(event)) {
      return;
    }

    if (event.key === 'Tab') {
      handleTabNavigation(event);
    }
  };
</script>

{#if isOpen}
  <!-- svelte-ignore a11y_click_events_have_key_events -->
  <div
    class="modal-overlay"
    class:entering={!isExiting}
    class:exiting={isExiting}
    onclick={handleOverlayClick}
    role="presentation"
  >
    <!-- svelte-ignore a11y_interactive_supports_focus -->
    <div
      bind:this={modalElement}
      class="modal"
      class:entering={!isExiting}
      class:exiting={isExiting}
      onclick={(e) => e.stopPropagation()}
      onkeydown={handleKeydown}
      role="dialog"
      aria-modal="true"
    >
      <div class="modal-content">
        {@render children()}
      </div>
      <div class="modal-actions">
        <button
          bind:this={cancelButton}
          type="button"
          class="ui-ghost-btn"
          onclick={handleCancel}
          disabled={isBusy}
        >
          {cancelText}
        </button>
        <button
          bind:this={confirmButton}
          type="button"
          class={confirmVariant}
          onclick={handleConfirm}
          disabled={isBusy}
        >
          {#if isBusy}
            Processing...
          {:else}
            {confirmText}
          {/if}
        </button>
      </div>
    </div>
  </div>
{/if}

<style>
  .modal-overlay {
    position: fixed;
    inset: 0;
    background: rgba(0, 0, 0, 0.7);
    display: flex;
    align-items: center;
    justify-content: center;
    z-index: 100;
    opacity: 0;
  }

  .modal-overlay.entering {
    animation: overlayFadeIn 180ms ease-out forwards;
  }

  .modal-overlay.exiting {
    animation: overlayFadeOut 180ms ease-in forwards;
  }

  .modal {
    background: linear-gradient(160deg, rgba(20, 28, 43, 0.98), rgba(13, 18, 28, 0.98));
    border: 1px solid rgba(164, 182, 216, 0.3);
    border-radius: 1rem;
    padding: 1.5rem;
    max-width: 22rem;
    width: 90%;
    opacity: 0;
    transform: scale(0.96);
  }

  .modal.entering {
    animation: modalEnter 180ms ease-out forwards;
  }

  .modal.exiting {
    animation: modalExit 180ms ease-in forwards;
  }

  @keyframes overlayFadeIn {
    from { opacity: 0; }
    to { opacity: 1; }
  }

  @keyframes overlayFadeOut {
    from { opacity: 1; }
    to { opacity: 0; }
  }

  @keyframes modalEnter {
    from {
      opacity: 0;
      transform: scale(0.96);
    }
    to {
      opacity: 1;
      transform: scale(1);
    }
  }

  @keyframes modalExit {
    from {
      opacity: 1;
      transform: scale(1);
    }
    to {
      opacity: 0;
      transform: scale(0.96);
    }
  }

  .modal-content {
    margin-bottom: 1.25rem;
    min-width: 0;
  }

  .modal-content :global(p) {
    margin: 0 0 0.5rem;
    color: var(--fg);
    line-height: 1.5;
    overflow-wrap: anywhere;
    word-break: break-word;
  }

  .modal-content :global(p:last-child) {
    margin-bottom: 0;
  }

  .modal-content :global(.subtle) {
    color: var(--muted);
    font-size: 0.9rem;
  }

  .modal-content :global(strong) {
    color: var(--accent);
    overflow-wrap: anywhere;
    word-break: break-word;
  }

  .modal-content :global(.danger-text) {
    color: var(--danger);
  }

  .modal-actions {
    display: flex;
    gap: 0.5rem;
    justify-content: flex-end;
  }

  button {
    border: 0;
    border-radius: 0.6rem;
    padding: 0.62rem 0.95rem;
    background: var(--accent);
    color: #1e2030;
    font: inherit;
    font-weight: 600;
    cursor: pointer;
    transition: opacity 0.15s ease;
  }

  button:disabled {
    opacity: 0.6;
    cursor: not-allowed;
  }

  .primary {
    background: var(--accent);
    color: #1e2030;
  }

  .danger {
    background: color-mix(in srgb, var(--danger) 92%, #1e2030);
    color: white;
  }

  @media (prefers-reduced-motion: reduce) {
    .modal-overlay,
    .modal {
      animation: none;
      opacity: 1;
      transform: none;
    }
  }
</style>

// web/src/components/ui/confirm-dialog.tsx
import type { ReactElement, ReactNode } from 'react';
import { useEffect, useRef, useState, useCallback } from 'react';

interface ConfirmDialogProps {
  cancelText?: string;
  children: ReactNode;
  confirmText: string;
  confirmVariant?: 'primary' | 'danger';
  initialFocus?: 'confirm' | 'cancel';
  isBusy: boolean;
  isOpen: boolean;
  onCancel: () => void;
  onConfirm: () => void;
}

const FIRST_INDEX = 0;
const FOCUS_TIMEOUT_MS = 0;
const LAST_INDEX_OFFSET = 1;
const TRANSITION_DURATION_MS = 180;
const ZERO_LENGTH = 0;

export const ConfirmDialog = ({
  cancelText = 'Cancel',
  children,
  confirmText,
  confirmVariant = 'primary',
  initialFocus = 'cancel',
  isBusy,
  isOpen,
  onCancel,
  onConfirm,
}: ConfirmDialogProps): ReactElement | null => {
  const [isExiting, setIsExiting] = useState(false);
  const modalElement = useRef<HTMLDivElement>(null);
  const confirmButton = useRef<HTMLButtonElement>(null);
  const cancelButton = useRef<HTMLButtonElement>(null);
  const lastFocusedElement = useRef<HTMLElement | null>(null);

  useEffect(() => {
    if (isOpen) {
      setIsExiting(false);
      lastFocusedElement.current = document.activeElement as HTMLElement;
    }
  }, [isOpen]);

  useEffect(() => {
    if (isOpen && !isExiting) {
      const timer = setTimeout(() => {
        if (initialFocus === 'confirm' && confirmButton.current) {
          confirmButton.current.focus({ preventScroll: true });
        } else if (cancelButton.current) {
          cancelButton.current.focus({ preventScroll: true });
        }
      }, FOCUS_TIMEOUT_MS);
      return () => clearTimeout(timer);
    }
  }, [isOpen, isExiting, initialFocus]);

  const restoreFocus = useCallback(() => {
    if (lastFocusedElement.current && typeof lastFocusedElement.current.focus === 'function') {
      lastFocusedElement.current.focus({ preventScroll: true });
    }
  }, []);

  const handleCancel = useCallback(() => {
    if (isBusy) return;
    setIsExiting(true);
    setTimeout(() => {
      onCancel();
      restoreFocus();
    }, TRANSITION_DURATION_MS);
  }, [isBusy, onCancel, restoreFocus]);

  const handleConfirm = useCallback(() => {
    if (isBusy) return;
    onConfirm();
  }, [isBusy, onConfirm]);

  const handleOverlayClick = useCallback(() => {
    if (!isBusy) {
      handleCancel();
    }
  }, [isBusy, handleCancel]);

  const handleKeydown = useCallback(
    (event: React.KeyboardEvent) => {
      if (event.key === 'Escape' && !isBusy) {
        event.preventDefault();
        handleCancel();
        return;
      }

      if (event.key === 'Tab' && modalElement.current) {
        const focusableElements = modalElement.current?.querySelectorAll(
          'button, [href], input, select, textarea, [tabindex]:not([tabindex="-1"])',
        );
        if (!focusableElements || focusableElements.length === ZERO_LENGTH) return;

        const firstElement = focusableElements[FIRST_INDEX] as HTMLElement;
        const lastElement = focusableElements[focusableElements.length - LAST_INDEX_OFFSET] as HTMLElement;

        if (event.shiftKey && document.activeElement === firstElement) {
          event.preventDefault();
          lastElement.focus({ preventScroll: true });
        } else if (!event.shiftKey && document.activeElement === lastElement) {
          event.preventDefault();
          firstElement.focus({ preventScroll: true });
        }
      }
    },
    [isBusy, handleCancel],
  );

  if (!isOpen) return null;

  return (
    <div
      className={`modal-overlay ${isExiting ? 'exiting' : 'entering'}`}
      onClick={handleOverlayClick}
      role="presentation"
    >
      <div
        ref={modalElement}
        className={`modal ${isExiting ? 'exiting' : 'entering'}`}
        onClick={(event) => event.stopPropagation()}
        onKeyDown={handleKeydown}
        role="dialog"
        aria-modal="true"
      >
        <div className="modal-content">{children}</div>
        <div className="modal-actions">
          <button
            ref={cancelButton}
            type="button"
            className="ui-ghost-btn"
            onClick={handleCancel}
            disabled={isBusy}
          >
            {cancelText}
          </button>
          <button
            ref={confirmButton}
            type="button"
            className={confirmVariant}
            onClick={handleConfirm}
            disabled={isBusy}
          >
            {isBusy ? 'Processing...' : confirmText}
          </button>
        </div>
      </div>
    </div>
  );
}
