// web/src/lib/components/ui/SkeletonVideoList.svelte
<script lang="ts">
  import SkeletonThumbnail from './SkeletonThumbnail.svelte';
  import SkeletonText from './SkeletonText.svelte';

  interface Props {
    count?: number;
  }

  let { count = 5 }: Props = $props();
</script>

<div class="skeleton-video-list">
  {#each Array(count) as _}
    <div class="skeleton-video-row">
      <SkeletonThumbnail width="240px" aspectRatio="16 / 9" />
      <div class="skeleton-video-info">
        <SkeletonText lines={2} width="85%" />
      </div>
    </div>
  {/each}
</div>

<style>
  .skeleton-video-list {
    display: flex;
    flex-direction: column;
    gap: 0.75rem;
  }

  .skeleton-video-row {
    width: 100%;
    display: flex;
    align-items: stretch;
    gap: 1rem;
    padding: 1rem;
    border: 1px solid color-mix(in srgb, var(--border) 75%, transparent);
    border-radius: 0.75rem;
    background: color-mix(in srgb, var(--bg-soft) 62%, var(--surface));
  }

  .skeleton-video-info {
    flex: 1;
    min-width: 0;
    display: flex;
    flex-direction: column;
    justify-content: center;
  }

  @media (max-width: 700px) {
    .skeleton-video-row {
      flex-direction: column;
    }
  }
</style>

// web/src/components/ui/SkeletonVideoList.tsx
import type { ReactElement } from 'react';
import { SkeletonText } from './SkeletonText';
import { SkeletonThumbnail } from './SkeletonThumbnail';

interface SkeletonVideoListProps {
  count?: number;
}

const DEFAULT_COUNT = 5;

export const SkeletonVideoList = ({ count = DEFAULT_COUNT }: SkeletonVideoListProps): ReactElement => {
  return (
    <div className="skeleton-video-list">
      {Array.from({ length: count }).map((_, index) => (
        <div key={index} className="skeleton-video-row">
          <SkeletonThumbnail width="240px" aspectRatio="16 / 9" />
          <div className="skeleton-video-info">
            <SkeletonText lines={2} width="85%" />
          </div>
        </div>
      ))}
    </div>
  );
}
