// web/src/components/layout/twitch-layout.tsx
import Box from '@mui/material/Box';
import { useCallback, useEffect, useRef, type ReactElement, type ReactNode } from 'react';
import { useRouter } from '../../hooks/use-router';
import AppVersion from './app-version';

const POPSTATE_TYPE = 'popstate';

interface TwitchLayoutProps {
  children: ReactNode;
}

/**
 * Twitch layout component with focus management.
 * Ported from Svelte twitch-layout.svelte.
 */
export default function TwitchLayout({ children }: TwitchLayoutProps): ReactElement {
  const mainElementRef = useRef<HTMLElement>(null);
  const { afterNavigate } = useRouter();

  // Focus management: only on forward navigations, not back/forward
  const handleNavigation = useCallback(
    (navigation: { from?: string; to: string; type: string }) => {
      // Skip focus management for popstate (back/forward) to preserve scroll position
      if (navigation.type === POPSTATE_TYPE) {
        return;
      }

      // Focus the main container for keyboard navigation, but don't scroll
      if (mainElementRef.current) {
        mainElementRef.current.focus({ preventScroll: true });
      }
    },
    [],
  );

  // Register navigation callback
  useEffect(() => {
    const cleanup = afterNavigate(handleNavigation);
    return cleanup;
  }, [afterNavigate, handleNavigation]);

  return (
    <Box sx={{ display: 'flex', flexDirection: 'column', height: '100vh' }}>
      <Box
        component="main"
        ref={mainElementRef}
        tabIndex={-1}
        aria-label="Twitch Relay main content"
        sx={{ flexGrow: 1, outline: 'none' }}
      >
        {children}
      </Box>

      <AppVersion />
    </Box>
  );
}

// web/src/lib/layouts/twitch-layout.svelte
<script lang="ts">
  import { onDestroy, onMount } from 'svelte';

  import AppVersion from '$lib/components/app-version.svelte';
  import { afterNavigate } from '$lib/router/router.svelte';

  const POPSTATE_TYPE = 'popstate';

  const { children } = $props<{ children?: import('svelte').Snippet }>();
  let mainElement = $state<HTMLElement | undefined>(undefined);

  onMount(() => {
    // Set Twitch theme on body
    document.body.dataset.theme = 'twitch';
  });

  onDestroy(() => {
    // Clean up theme on destroy
    delete document.body.dataset.theme;
  });

  // Focus management: only on forward navigations, not back/forward
  afterNavigate((navigation) => {
    // Skip focus management for popstate (back/forward) to preserve scroll position
    if (navigation.type === POPSTATE_TYPE) {
      return;
    }

    // Focus the main container for keyboard navigation, but don't scroll
    if (mainElement) {
      mainElement.focus({ preventScroll: true });
    }
  });
</script>

<div class="twitch-app">
  <main
    bind:this={mainElement}
    class="twitch-main"
    tabindex="-1"
    aria-label="Twitch Relay main content"
  >
    {@render children?.()}
  </main>

  <AppVersion />
</div>

<style>
  .twitch-app {
    min-height: 100dvh;
    box-sizing: border-box;
    display: flex;
    flex-direction: column;
    background: radial-gradient(
      circle at 20% -10%,
      color-mix(in srgb, var(--surface-2) 88%, black) 0%,
      var(--bg-soft) 45%,
      var(--bg) 100%
    );
    color: var(--fg);
  }

  .twitch-main {
    flex: 1;
    padding: 1rem;
    display: flex;
    flex-direction: column;
    align-items: center;
  }

  .twitch-main:focus {
    outline: none;
  }

  :global(.twitch-app .app-version) {
    margin-top: auto;
    padding: 1rem;
  }
</style>
