// web/src/pages/twitch-channel-page.tsx
import { useCallback, useEffect, useMemo, useState, type ReactElement } from 'react';
import {
  getChannels,
  getRecordingRules,
  upsertRecordingRule,
} from '../api-client';
import { TwitchPanel } from '../components/twitch/twitch-panel';
import { LoadedFade } from '../components/ui/loaded-fade';
import { useRouter } from '../hooks/use-router';
import { navigate } from '../router/routes';
import { useRecordingRuleForm } from './twitch-channel/recording-rule-form';

const DEFAULT_QUALITY = '720p60';
const FAILED_TO_LOAD = 'failed to load channel settings';
const FAILED_TO_SAVE = 'failed to save settings';
const MIN_MESSAGE_LENGTH = 0;

const QUALITY_OPTIONS = [
  '1080p',
  '1080p60',
  '160p',
  '360p',
  '480p',
  '720p',
  '720p60',
  'best',
  'source',
];

export const TwitchChannelPage = (): ReactElement => {
  const { page } = useRouter();

  // Get login from router params
  const channelLogin = useMemo(
    () => (page.params.login ?? '').trim().toLowerCase(),
    [page.params.login],
  );

  // State
  const [channelExists, setChannelExists] = useState(true);
  const [channelDisplayName, setChannelDisplayName] = useState('');
  const [isLoading, setIsLoading] = useState(true);
  const [isSaving, setIsSaving] = useState(false);

  // Form state from custom hook
  const {
    enabled,
    quality,
    stopWhenOffline,
    maxDurationMinutesInput,
    keepLastVideosInput,
    errorMessage,
    successMessage,
    setEnabled,
    setQuality,
    setStopWhenOffline,
    setMaxDurationMinutesInput,
    setKeepLastVideosInput,
    setErrorMessage,
    setSuccessMessage,
    applyRule,
    clearMessages,
    scheduleSuccessDismiss,
    buildSavePayload,
    cleanupTimer,
  } = useRecordingRuleForm();

  const readMessage = useCallback((error: unknown, fallback: string): string => {
    if (error instanceof Error && error.message.trim().length > MIN_MESSAGE_LENGTH) {
      return error.message;
    }
    return fallback;
  }, []);

  const handleLoadError = useCallback(
    (error: unknown): void => {
      setErrorMessage(readMessage(error, FAILED_TO_LOAD));
    },
    [readMessage, setErrorMessage],
  );

  const loadChannels = useCallback(async (): Promise<void> => {
    const [channels, rules] = await Promise.all([getChannels(), getRecordingRules()]);
    const channel = channels.find((entry) => entry.login === channelLogin);
    setChannelExists(Boolean(channel));
    setChannelDisplayName(channel?.display_name ?? channel?.login ?? channelLogin);

    const rule = rules.find((entry) => entry.channel_login === channelLogin);
    applyRule(rule ?? undefined);
  }, [channelLogin, applyRule]);

  const loadPageState = useCallback(async (): Promise<void> => {
    setIsLoading(true);
    clearMessages();

    try {
      await loadChannels();
    } catch (error) {
      handleLoadError(error);
    } finally {
      setIsLoading(false);
    }
  }, [loadChannels, handleLoadError, clearMessages]);

  const handleSaveError = useCallback(
    (error: unknown): void => {
      setErrorMessage(readMessage(error, FAILED_TO_SAVE));
    },
    [readMessage, setErrorMessage],
  );

  const saveSettings = useCallback(
    (event: React.FormEvent): void => {
      event.preventDefault();
      setIsSaving(true);
      clearMessages();

      void (async (): Promise<void> => {
        try {
          const saved = await upsertRecordingRule(buildSavePayload(channelLogin));

          applyRule(saved);
          setSuccessMessage('Saved');
          scheduleSuccessDismiss();
        } catch (error) {
          handleSaveError(error);
        } finally {
          setIsSaving(false);
        }
      })();
    },
    [buildSavePayload, channelLogin, applyRule, scheduleSuccessDismiss, handleSaveError, clearMessages],
  );

  const goBack = useCallback((): void => {
    navigate('/twitch');
  }, []);

  // Initialize on mount
  useEffect(() => {
    void loadPageState();
  }, [loadPageState]);

  // Cleanup timer on unmount
  useEffect(() => cleanupTimer, [cleanupTimer]);

  return (
    <TwitchPanel>
      <div className="channel-settings-page">
        <header className="ui-page-header">
          <div>
            <p className="ui-page-eyebrow">Channel Settings</p>
            <h1 className="ui-page-title">{channelDisplayName}</h1>
            <p className="ui-page-subtle">
              Configure recording behavior for <strong>{channelLogin}</strong>
            </p>
          </div>
          <button type="button" className="ui-nav-chip" onClick={goBack}>
            Back to channels
          </button>
        </header>

        {errorMessage !== null && errorMessage !== '' && (
          <p className="ui-error" role="alert">
            {errorMessage}
          </p>
        )}
        {successMessage !== null && successMessage !== '' && (
          <p className="ui-alert-success" role="status">
            {successMessage}
          </p>
        )}

        {!isLoading && !channelExists && (
          <p className="ui-muted">
            This channel is not in your list. Add it on the front page first.
          </p>
        )}

        {!isLoading && channelExists && (
          <LoadedFade loaded={true}>
            <form className="channel-settings-form" onSubmit={(event) => { void saveSettings(event); }}>
              <label className="toggle-row">
                <input
                  type="checkbox"
                  checked={enabled}
                  onChange={(event) => { setEnabled(event.target.checked); }}
                />
                <span>Enable auto-record</span>
              </label>

              <label>
                Quality
                <span className="channel-quality-select-wrap">
                  <select value={quality} onChange={(event) => { setQuality(event.target.value); }}>
                    {QUALITY_OPTIONS.map((option) => (
                      <option key={option} value={option}>
                        {option}
                      </option>
                    ))}
                  </select>
                </span>
              </label>

              <label className="toggle-row">
                <input
                  type="checkbox"
                  checked={stopWhenOffline}
                  onChange={(event) => { setStopWhenOffline(event.target.checked); }}
                />
                <span>Stop when channel goes offline</span>
              </label>

              <label>
                Max duration minutes
                <input
                  type="number"
                  min="1"
                  step="1"
                  value={maxDurationMinutesInput}
                  onChange={(event) => { setMaxDurationMinutesInput(event.target.value); }}
                  placeholder="Leave empty for no limit"
                  inputMode="numeric"
                />
              </label>

              <label>
                Keep last videos
                <input
                  type="number"
                  min="1"
                  step="1"
                  value={keepLastVideosInput}
                  onChange={(event) => { setKeepLastVideosInput(event.target.value); }}
                  placeholder="Leave empty for no limit"
                  inputMode="numeric"
                />
              </label>
              <p className="hint">
                Applies to completed recordings only. Older completed files are deleted automatically.
              </p>

              <div className="ui-action-row">
                <button className="ui-button-primary" type="submit" disabled={isSaving}>
                  {isSaving ? 'Saving...' : 'Save settings'}
                </button>
              </div>
            </form>
          </LoadedFade>
        )}
      </div>
    </TwitchPanel>
  );
};

// web/src/lib/pages/twitch-channel-page.svelte
<script lang="ts">
  import { onDestroy, onMount } from 'svelte';

  import {
    type RecordingRule,
    getChannels,
    getRecordingRules,
    upsertRecordingRule
  } from '$lib/api-client';
  import { navigate, page } from '$lib/router/router.svelte';
  import LoadedFade from '$lib/components/loaded-fade.svelte';
  import TwitchPanel from '$lib/components/twitch/twitch-panel.svelte';

  const DEFAULT_QUALITY = 'best';
  const FAILED_TO_LOAD = 'failed to load channel settings';
  const FAILED_TO_SAVE = 'failed to save settings';
  const MIN_VALUE_ERROR = 'must be at least 1';
  const NOT_WHOLE_NUMBER_ERROR = 'must be a whole number';
  const SUCCESS_DISMISS_MS = 3500;

  // Get login from router params
  const login = $derived((page as unknown as { params?: { login?: string } }).params?.login ?? '');

  const QUALITY_OPTIONS = ['1080p', '1080p60', '160p', '360p', '480p', '720p', '720p60', 'best', 'source'];

  const channelLogin = $derived(login.trim().toLowerCase());
  let channelExists = $state(true);
  let channelDisplayName = $state('');

  let isLoading = $state(true);
  let isSaving = $state(false);
  let errorMessage = $state<string>();
  let successMessage = $state<string>();

  let enabled = $state(false);
  let quality = $state(DEFAULT_QUALITY);
  let stopWhenOffline = $state(true);
  let maxDurationMinutesInput = $state('');
  let keepLastVideosInput = $state('');

  // Auto-dismiss success message timer
  let successDismissTimer = $state<ReturnType<typeof setTimeout>>();

  const scheduleSuccessDismiss = (): void => {
    if (successDismissTimer) {
      clearTimeout(successDismissTimer);
    }
    successDismissTimer = setTimeout(() => {
      successMessage = undefined;
    }, SUCCESS_DISMISS_MS);
  };

  onDestroy(() => {
    if (successDismissTimer) {
      clearTimeout(successDismissTimer);
    }
  });

  onMount(async () => {
    await loadPageState();
  });

  const loadPageState = async (): Promise<void> => {
    isLoading = true;
    errorMessage = undefined;
    successMessage = undefined;

    try {
      const [channels, rules] = await Promise.all([getChannels(), getRecordingRules()]);
      const channel = channels.find((entry) => entry.login === channelLogin);
      channelExists = Boolean(channel);
      channelDisplayName = channel?.display_name || channel?.login || channelLogin;

      const rule = rules.find((entry) => entry.channel_login === channelLogin);
      applyRule(rule ?? undefined);
    } catch (error) {
      errorMessage = readMessage(error, FAILED_TO_LOAD);
    } finally {
      isLoading = false;
    }
  };

  const applyRule = (rule: RecordingRule | undefined): void => {
    if (!rule) {
      enabled = false;
      quality = DEFAULT_QUALITY;
      stopWhenOffline = true;
      maxDurationMinutesInput = '';
      keepLastVideosInput = '';
      return;
    }

    ({ enabled, quality, stop_when_offline: stopWhenOffline } = rule);
    quality = quality || DEFAULT_QUALITY;
    maxDurationMinutesInput = rule.max_duration_minutes === undefined ? '' : String(rule.max_duration_minutes);
    keepLastVideosInput = rule.keep_last_videos === undefined ? '' : String(rule.keep_last_videos);
  };

  const parseOptionalPositiveInt = (
    value: string | number | undefined,
    label: string
  ): number | undefined => {
    let normalized: string;
    if (value === undefined) {
      normalized = '';
    } else if (typeof value === 'number') {
      normalized = String(value);
    } else {
      normalized = value;
    }
    const trimmed = normalized.trim();
    if (!trimmed) {
      return undefined;
    }

    if (!/^\d+$/.test(trimmed)) {
      throw new Error(`${label} ${NOT_WHOLE_NUMBER_ERROR}`);
    }

    const MIN_VALUE = 1;

    const parsed = Number(trimmed);
    if (!Number.isSafeInteger(parsed) || parsed < MIN_VALUE) {
      throw new Error(`${label} ${MIN_VALUE_ERROR}`);
    }

    return parsed;
  };

  const saveSettings = async (event: SubmitEvent): Promise<void> => {
    event.preventDefault();
    isSaving = true;
    errorMessage = undefined;
    successMessage = undefined;

    try {
      const maxDurationMinutes = parseOptionalPositiveInt(maxDurationMinutesInput, 'Max duration minutes');
      const keepLastVideos = parseOptionalPositiveInt(keepLastVideosInput, 'Keep last videos');

      const saved = await upsertRecordingRule({
        channel_login: channelLogin,
        enabled,
        keep_last_videos: keepLastVideos,
        max_duration_minutes: maxDurationMinutes,
        quality,
        stop_when_offline: stopWhenOffline
      });

      applyRule(saved);
      successMessage = 'Saved';
      scheduleSuccessDismiss();
    } catch (error) {
      errorMessage = readMessage(error, FAILED_TO_SAVE);
    } finally {
      isSaving = false;
    }
  };

  const goBack = (): void => {
    navigate('/twitch');
  };

  const MIN_MESSAGE_LENGTH = 0;

  const readMessage = (error: unknown, fallback: string): string => {
    if (error instanceof Error && error.message.trim().length > MIN_MESSAGE_LENGTH) {
      return error.message;
    }
    return fallback;
  };
</script>

<TwitchPanel>
  <header class="ui-page-header">
    <div>
      <p class="ui-page-eyebrow">Channel Settings</p>
      <h1 class="ui-page-title">{channelDisplayName}</h1>
      <p class="ui-page-subtle">Configure recording behavior for <strong>{channelLogin}</strong></p>
    </div>
    <button type="button" class="ui-nav-chip" onclick={goBack}>Back to channels</button>
  </header>

  {#if errorMessage}
    <p class="ui-error" role="alert">{errorMessage}</p>
  {/if}
  {#if successMessage}
    <p class="ui-alert-success" role="status">{successMessage}</p>
  {/if}

  {#if !isLoading && !channelExists}
    <p class="ui-muted">This channel is not in your list. Add it on the front page first.</p>
  {:else if !isLoading}
    <LoadedFade loaded={true}>
      <form class="ui-form" onsubmit={saveSettings}>
        <label class="toggle-row">
          <input type="checkbox" bind:checked={enabled} />
          <span>Enable auto-record</span>
        </label>

        <label>
          Quality
          <select bind:value={quality}>
            {#each QUALITY_OPTIONS as option (option)}
              <option value={option}>{option}</option>
            {/each}
          </select>
        </label>

        <label class="toggle-row">
          <input type="checkbox" bind:checked={stopWhenOffline} />
          <span>Stop when channel goes offline</span>
        </label>

        <label>
          Max duration minutes
          <input
            type="number"
            min="1"
            step="1"
            bind:value={maxDurationMinutesInput}
            placeholder="Leave empty for no limit"
            inputmode="numeric"
          />
        </label>

        <label>
          Keep last videos
          <input
            type="number"
            min="1"
            step="1"
            bind:value={keepLastVideosInput}
            placeholder="Leave empty for no limit"
            inputmode="numeric"
          />
        </label>
        <p class="hint">Applies to completed recordings only. Older completed files are deleted automatically.</p>

        <div class="ui-action-row">
          <button class="ui-button-primary" type="submit" disabled={isSaving}>{isSaving ? 'Saving...' : 'Save settings'}</button>
        </div>
      </form>
    </LoadedFade>
  {/if}
</TwitchPanel>

<style>
  /* Local form styles - kept for channel-specific layout */
  .toggle-row {
    display: inline-flex;
    align-items: center;
    gap: 0.55rem;
    font-weight: 500;
  }

  /* Form field and input styles - kept for specific layout needs */
  label {
    display: grid;
    gap: 0.35rem;
    font-weight: 600;
  }

  .toggle-row {
    display: inline-flex;
    align-items: center;
    gap: 0.55rem;
    font-weight: 500;
  }

  input,
  select {
    border: 1px solid rgba(160, 181, 216, 0.35);
    background: rgba(8, 12, 19, 0.9);
    color: var(--fg);
    border-radius: 0.6rem;
    padding: 0.68rem 0.76rem;
    font: inherit;
  }

  /* Local override to style button in header (overrides generic button selector) */
  .ui-page-header :global(.ui-nav-chip) {
    background: transparent;
    border: 1px solid color-mix(in srgb, var(--border) 78%, transparent);
    color: var(--fg);
    padding: 0.4rem 0.8rem;
    font-size: 0.85rem;
    min-height: 2rem;
  }

  .ui-page-header :global(.ui-nav-chip:hover) {
    border-color: var(--accent-border);
    background: var(--accent-soft);
  }

  /* Hint text - channel settings specific */
  .hint {
    margin: 0;
    color: var(--muted);
    font-size: 0.84rem;
  }

  @media (max-width: 640px) {
    .ui-page-header {
      flex-direction: column;
      align-items: flex-start;
    }

    .ui-action-row {
      justify-content: flex-start;
    }
  }
</style>
