// web/src/pages/YouTubeChannelPage.tsx
import { useCallback, useEffect, useState } from 'react';
import type { ReactElement } from 'react';
import { SkeletonVideoList, ErrorState, EmptyState, LoadedFade } from '../components/ui';
import { YouTubeVideoRow } from '../components/youtube';
import {
  getYouTubeChannelVideos,
  refreshYouTubeChannelVideos,
  type YoutubeVideo,
} from '../lib/api-client';
import { navigate } from '../router';

interface YouTubeChannelPageProps {
  channel_id: string;
}

const ZERO = 0;
const DEFAULT_CHANNEL_NAME = 'Channel';
const DEFAULT_SKELETON_COUNT = 6;
const ERROR_NO_ID = 'No channel ID provided';
const ERROR_NO_VIDEOS_DESC = "This channel doesn't have any videos available.";
const ERROR_NO_VIDEOS_TITLE = 'No videos found';
const ERROR_LOAD_FAILED = 'Failed to load videos';

export const YouTubeChannelPage = ({ channel_id }: YouTubeChannelPageProps): ReactElement => {
  const [videos, setVideos] = useState<readonly YoutubeVideo[]>([]);
  const [isLoading, setIsLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);
  const [channelName, setChannelName] = useState(DEFAULT_CHANNEL_NAME);

  const returnUrl = `/youtube/channel/${channel_id}`;

  const updateChannelName = (channelVideos: readonly YoutubeVideo[]): void => {
    if (channelVideos.length > ZERO) {
      setChannelName(channelVideos[ZERO].author);
    }
  };

  const loadInitialChannelVideos = async (): Promise<boolean> => {
    const { fromCache, videos: fetchedVideos } = await getYouTubeChannelVideos(channel_id);
    setVideos(fetchedVideos);
    updateChannelName(fetchedVideos);
    setIsLoading(!fromCache);
    return fromCache;
  };

  const refreshChannelVideos = async (): Promise<void> => {
    const refreshed = await refreshYouTubeChannelVideos(channel_id);
    setVideos(refreshed.videos);
    updateChannelName(refreshed.videos);
  };

  const validateChannelId = (): boolean => {
    if (channel_id) {
      return true;
    }
    setError(ERROR_NO_ID);
    setIsLoading(false);
    return false;
  };

  const startLoading = (): void => {
    setIsLoading(true);
    setError(null);
  };

  const setLoadError = (error_: unknown): void => {
    const errorMessage = error_ instanceof Error ? error_.message : ERROR_LOAD_FAILED;
    setError(errorMessage);
  };

  const loadChannelVideos = async (): Promise<void> => {
    if (!validateChannelId()) {
      return;
    }

    startLoading();

    try {
      const fromCache = await loadInitialChannelVideos();

      if (!fromCache) {
        await refreshChannelVideos();
      }
    } catch (error_) {
      setLoadError(error_);
    } finally {
      setIsLoading(false);
    }
  };

  useEffect(() => {
    void loadChannelVideos();
  }, [channel_id]);

  const openVideo = useCallback(
    (videoId: string): void => {
      navigate(`/youtube/watch/${encodeURIComponent(videoId)}`, {
        state: { youtubeReturnUrl: returnUrl },
      });
    },
    [returnUrl],
  );

  const goBack = useCallback((): void => {
    navigate('/youtube');
  }, []);

  return (
    <section className="ui-page-panel">
      <header className="panel-header">
        <div className="panel-title">
          <button type="button" className="ui-nav-chip" onClick={goBack}>
            Back
          </button>
          <h1 className="ui-page-title">{channelName}</h1>
          <p className="ui-page-subtle">Latest Videos</p>
        </div>
      </header>

      {isLoading ? (
        <SkeletonVideoList count={DEFAULT_SKELETON_COUNT} />
      ) : error !== null && error !== '' ? (
        <ErrorState message={error} onRetry={loadChannelVideos} isRetrying={isLoading} />
      ) : videos.length === ZERO ? (
        <EmptyState
          title={ERROR_NO_VIDEOS_TITLE}
          description={ERROR_NO_VIDEOS_DESC}
          variant="videos"
        />
      ) : (
        <LoadedFade loaded={true}>
          <div className="youtube-video-list">
            {videos.map((video) => (
              <YouTubeVideoRow
                key={video.video_id}
                video={video}
                onClick={() => {
                  openVideo(video.video_id);
                }}
              />
            ))}
          </div>
        </LoadedFade>
      )}
    </section>
  );
}

// web/src/lib/pages/YouTubeChannelPage.svelte
<script lang="ts">
  import { onMount } from 'svelte';
  import { navigate } from '$lib/router/router.svelte';
  import { getYouTubeChannelVideos, refreshYouTubeChannelVideos } from '$lib/api-client';
  import type { YoutubeVideo } from '$lib/api-client';
  import LoadedFade from '$lib/components/LoadedFade.svelte';
  import YouTubeVideoRow from '$lib/components/youtube/YouTubeVideoRow.svelte';
  import { SkeletonVideoList, ErrorState, EmptyState } from '$lib/components/ui';

  interface Props {
    channel_id: string;
  }

  let { channel_id }: Props = $props();

  let videos = $state<YoutubeVideo[]>([]);
  let isLoading = $state(true);
  let error = $state<string | null>(null);
  let channelName = $state('Channel');

  const returnUrl = $derived(`/youtube/channel/${channel_id}`);

  async function loadChannelVideos(): Promise<void> {
    if (!channel_id) {
      error = 'No channel ID provided';
      isLoading = false;
      return;
    }

    isLoading = true;
    error = null;

    try {
      const result = await getYouTubeChannelVideos(channel_id);
      videos = result.videos;
      if (result.videos.length > 0) {
        channelName = result.videos[0].author;
      }
      isLoading = result.fromCache === false;

      if (!result.fromCache) {
        const refreshed = await refreshYouTubeChannelVideos(channel_id);
        videos = refreshed.videos;
        if (refreshed.videos.length > 0) {
          channelName = refreshed.videos[0].author;
        }
      }
    } catch (e) {
      error = e instanceof Error ? e.message : 'Failed to load videos';
    } finally {
      isLoading = false;
    }
  }

  onMount(loadChannelVideos);

  function openVideo(videoId: string) {
    navigate(`/youtube/watch/${encodeURIComponent(videoId)}`, {
      state: { youtubeReturnUrl: returnUrl }
    });
  }

  function goBack() {
    navigate('/youtube');
  }
</script>

<section class="ui-page-panel">
  <header class="panel-header">
    <div class="panel-title">
      <button type="button" class="ui-nav-chip" onclick={goBack}>Back</button>
      <h1 class="ui-page-title">{channelName}</h1>
      <p class="ui-page-subtle">Latest Videos</p>
    </div>
  </header>

  {#if isLoading}
    <SkeletonVideoList count={6} />
  {:else if error}
    <ErrorState
      message={error}
      onRetry={loadChannelVideos}
      isRetrying={isLoading}
    />
  {:else if videos.length === 0}
    <EmptyState
      title="No videos found"
      description="This channel doesn't have any videos available."
      variant="videos"
    />
  {:else}
    <LoadedFade loaded={true}>
      <div class="youtube-video-list">
        {#each videos as video (video.video_id)}
          <YouTubeVideoRow {video} onClick={() => openVideo(video.video_id)} />
        {/each}
      </div>
    </LoadedFade>
  {/if}
</section>

<style>
  /* Width override: this page uses 46rem instead of default 42rem */
  .ui-page-panel {
    width: min(46rem, 100%);
  }

  /* Header layout - YouTube specific */
  .panel-header {
    display: flex;
    align-items: center;
    justify-content: space-between;
    gap: 1rem;
    margin-bottom: 1rem;
  }

  .panel-title {
    min-width: 0;
  }

  .panel-title > .ui-nav-chip {
    margin-bottom: 0.5rem;
  }

  .ui-page-title {
    font-size: clamp(1.5rem, 4vw, 2rem);
  }

  .youtube-video-list {
    display: flex;
    flex-direction: column;
    gap: 0.75rem;
  }
</style>
