// web/src/pages/YouTubePlaylistsPage.tsx
import { useCallback, useEffect, useState } from 'react';
import type { ReactElement } from 'react';
import {
  SkeletonMediaList,
  ErrorState,
  EmptyState,
  LoadedFade,
  MediaRow,
  MediaRowMeta,
} from '../components/ui';
import { YouTubeShell } from '../components/youtube';
import { getYouTubePlaylists } from '../lib/api-client';
import type { YoutubePlaylist } from '../lib/api-client';
import { getYouTubePlaylistThumbnailUrl } from '../lib/api-client/youtube-progress';
import { formatTimeAgo } from '../lib/youtube/format';
import { navigate } from '../router';

const FAILED_TO_LOAD = 'Failed to load playlists';
const INITIAL_SLICE_INDEX = 0;
const INITIAL_SLICE_LENGTH = 1;
const NO_PLAYLISTS_DESC = 'Create playlists in YouTube to see them here.';
const NO_PLAYLISTS_TITLE = 'No playlists found';
const SKELETON_COUNT = 6;

export const YouTubePlaylistsPage = (): ReactElement => {
  const [playlists, setPlaylists] = useState<readonly YoutubePlaylist[]>([]);
  const [isLoading, setIsLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);

  const loadPlaylists = useCallback(async (): Promise<void> => {
    setIsLoading(true);
    setError(null);
    try {
      const data = await getYouTubePlaylists();
      setPlaylists(data);
    } catch (error_) {
      const errorMessage = error_ instanceof Error ? error_.message : FAILED_TO_LOAD;
      setError(errorMessage);
    } finally {
      setIsLoading(false);
    }
  }, []);

  useEffect(() => {
    void loadPlaylists();
  }, [loadPlaylists]);

  const handlePlaylistClick = useCallback((playlistId: string): void => {
    navigate(`/youtube/playlist/${encodeURIComponent(playlistId)}`);
  }, []);

  const getPlaylistInitial = (title: string): string =>
    title.slice(INITIAL_SLICE_INDEX, INITIAL_SLICE_LENGTH).toUpperCase();

  return (
    <YouTubeShell activeTab="playlists" subtitle="Your playlists">
      {isLoading ? (
        <SkeletonMediaList count={SKELETON_COUNT} />
      ) : error !== null && error !== '' ? (
        <ErrorState message={error} onRetry={loadPlaylists} isRetrying={isLoading} />
      ) : playlists.length === 0 ? (
        <EmptyState
          title={NO_PLAYLISTS_TITLE}
          description={NO_PLAYLISTS_DESC}
          variant="playlists"
        />
      ) : (
        <LoadedFade loaded={true}>
          <div className="ui-list">
            {playlists.map((playlist) => (
              <MediaRow
                key={playlist.playlist_id}
                title={playlist.title}
                onClick={() => {
                  handlePlaylistClick(playlist.playlist_id);
                }}
                extraClass="youtube-playlist-row"
                visual={
                  <div className="playlist-thumbnail-container">
                    <img
                      className="ui-thumbnail playlist-thumbnail"
                      src={getYouTubePlaylistThumbnailUrl(playlist.playlist_id)}
                      alt={playlist.title}
                      loading="lazy"
                      onError={(e) => {
                        const img = e.currentTarget as HTMLImageElement;
                        img.style.display = 'none';
                        const fallback = img.nextElementSibling;
                        if (fallback instanceof HTMLElement) {
                          fallback.style.display = 'grid';
                        }
                      }}
                    />
                    <div className="playlist-thumbnail-fallback" style={{ display: 'none' }}>
                      {getPlaylistInitial(playlist.title)}
                    </div>
                  </div>
                }
                meta={
                  <MediaRowMeta>
                    <span className="ui-media-meta playlist-meta">
                      {playlist.video_count} videos · Updated {formatTimeAgo(playlist.updated)}
                    </span>
                  </MediaRowMeta>
                }
              />
            ))}
          </div>
        </LoadedFade>
      )}
    </YouTubeShell>
  );
}

// web/src/lib/pages/YouTubePlaylistsPage.svelte
<script lang="ts">
  import { onMount } from 'svelte';
  import { navigate } from '$lib/router/router.svelte';
  import { getYouTubePlaylists, getYouTubePlaylistThumbnailUrl } from '$lib/api-client';
  import type { YoutubePlaylist } from '$lib/api-client';
  import { formatTimeAgo } from '$lib/youtube/format';
  import { LoadedFade, YouTubeMediaRow, YouTubeShell } from '$lib/components/youtube';
  import { SkeletonMediaList, ErrorState, EmptyState } from '$lib/components/ui';

  let playlists = $state<YoutubePlaylist[]>([]);
  let isLoading = $state(true);
  let error = $state<string | null>(null);

  async function loadPlaylists(): Promise<void> {
    isLoading = true;
    error = null;
    try {
      playlists = await getYouTubePlaylists();
    } catch (e) {
      error = e instanceof Error ? e.message : 'Failed to load playlists';
    } finally {
      isLoading = false;
    }
  }

  onMount(loadPlaylists);

  function handlePlaylistClick(playlistId: string) {
    navigate(`/youtube/playlist/${encodeURIComponent(playlistId)}`);
  }

  function getThumbnailUrl(playlist: YoutubePlaylist): string {
    return getYouTubePlaylistThumbnailUrl(playlist.playlist_id);
  }

  function getPlaylistInitial(title: string): string {
    return title.slice(0, 1).toUpperCase();
  }
</script>

<YouTubeShell activeTab="playlists" subtitle="Your playlists">
  {#if isLoading}
    <SkeletonMediaList count={6} />
  {:else if error}
    <ErrorState
      message={error}
      onRetry={loadPlaylists}
      isRetrying={isLoading}
    />
  {:else if playlists.length === 0}
    <EmptyState
      title="No playlists found"
      description="Create playlists in YouTube to see them here."
      variant="playlists"
    />
  {:else}
    <LoadedFade loaded={true}>
      <div class="ui-list">
        {#each playlists as playlist (playlist.playlist_id)}
          {#snippet visual()}
            <div class="playlist-thumbnail-container">
              <img
                class="ui-thumbnail playlist-thumbnail"
                src={getThumbnailUrl(playlist)}
                alt={playlist.title}
                loading="lazy"
                onerror={(e) => {
                  const img = e.currentTarget as HTMLImageElement;
                  img.style.display = 'none';
                  const fallback = img.nextElementSibling as HTMLElement | null;
                  if (fallback) fallback.style.display = 'grid';
                }}
              />
              <div class="playlist-thumbnail-fallback" style="display: none;">
                {getPlaylistInitial(playlist.title)}
              </div>
            </div>
          {/snippet}

          {#snippet meta()}
            <span class="ui-media-meta playlist-meta">
              {playlist.video_count} videos · Updated {formatTimeAgo(playlist.updated)}
            </span>
          {/snippet}

          <YouTubeMediaRow
            title={playlist.title}
            onClick={() => handlePlaylistClick(playlist.playlist_id)}
            {visual}
            {meta}
            extraClass="youtube-playlist-row"
          />
        {/each}
      </div>
    </LoadedFade>
  {/if}
</YouTubeShell>

<style>
  .playlist-thumbnail-container {
    position: relative;
    width: 140px;
    height: 78px;
  }

  .playlist-thumbnail {
    width: 140px;
    height: 78px;
    border-radius: 0.5rem;
  }

  .playlist-thumbnail-fallback {
    position: absolute;
    top: 0;
    left: 0;
    width: 140px;
    height: 78px;
    border-radius: 0.5rem;
    display: none;
    place-items: center;
    text-transform: uppercase;
    font-weight: 700;
    font-size: 1.5rem;
    color: var(--fg);
    background: var(--surface-2);
  }

  :global(.youtube-playlist-row) {
    display: grid;
    grid-template-columns: 140px minmax(0, 1fr);
    align-items: center;
    gap: 0.75rem;
    padding: 0.8rem;
    text-align: left;
  }
</style>
