// web/src/lib/pages/twitch-recording-player-page.svelte
<script lang="ts">
  import { onDestroy } from 'svelte';
  import { navigate, page } from '$lib/router/router.svelte';
  import { createRecordingPlayerController } from './twitch-recording-player-page-controller.svelte';

  let isInitialized = $state(false);
  const playerElement: { current: HTMLVideoElement | null } = { current: null };
  const controller = createRecordingPlayerController();

  $effect(() => {
    controller.setPlayerElement(playerElement.current);
  });

  const goBack = (): void => navigate('/twitch/recordings');

  $effect(() => {
    const { query } = page as unknown as { query?: Record<string, string> };
    controller.setParams(query?.channel_login ?? '', query?.filename ?? '');
  });

  $effect(() => {
    if (
      playerElement.current === null
      || controller.channelLogin === ''
      || controller.filename === ''
      || isInitialized
    ) {
      return;
    }

    isInitialized = true;
    void controller.initializePlayer();
  });

  onDestroy(() => {
    controller.teardown();
  });
</script>

<section class="ui-page-panel ui-page-panel--wide">
  <header class="ui-page-header">
    <div>
      <p class="ui-page-eyebrow">Recording Playback</p>
      <h1 class="ui-page-title">{controller.channelLogin || 'unknown channel'}</h1>
      {#if controller.filename}
        <p class="ui-page-subtle" title={controller.filename}>{controller.filename}</p>
      {/if}
    </div>
    <button type="button" class="ui-nav-chip" onclick={goBack}>Back to recordings</button>
  </header>

  {#if !controller.channelLogin || !controller.filename}
    <p class="ui-error">Missing recording playback parameters.</p>
  {:else}
    <div class="player-wrapper">
      {#if controller.isLoading}
        <div class="player loading">
          <p class="ui-muted">Loading player...</p>
        </div>
      {/if}
      <video class="player" class:hidden={controller.isLoading} controls preload="auto" bind:this={playerElement.current}>
        Your browser cannot play this recording format.
      </video>
    </div>
    {#if controller.playbackError}
      <p class="ui-error" role="alert">{controller.playbackError}</p>
    {/if}
  {/if}
</section>

<style>
  /* Player-specific styles - not shared */
  .ui-page-panel--wide {
    display: grid;
    gap: 0.8rem;
  }

  .player-wrapper {
    width: 100%;
    aspect-ratio: 16 / 9;
    min-height: 16rem;
    max-height: min(74vh, 52rem);
    border: 1px solid rgba(180, 198, 236, 0.35);
    background: #000;
    overflow: hidden;
  }

  .player {
    width: 100%;
    height: 100%;
    border-radius: 0;
    border: none;
    background: #000;
    display: block;
  }

  .player.loading {
    width: 100%;
    height: 100%;
    display: flex;
    align-items: center;
    justify-content: center;
  }

  .player.hidden {
    display: none;
  }

  /* 720p-class landscape TV browsers (e.g., Xbox Edge) */
  @media screen
    and (min-width: 1000px)
    and (max-width: 1400px)
    and (min-height: 600px)
    and (max-height: 800px)
    and (orientation: landscape) {
    .player-wrapper {
      max-height: min(70vh, 600px);
    }
  }
</style>

// web/src/pages/twitch-recording-player-page.tsx
import { useCallback, useEffect, useRef, useState, type ReactElement } from 'react';
import { useRouter } from '../hooks/use-router';
import { navigate } from '../router/routes';
import {
  getRecordingWatchProgress,
  saveRecordingWatchProgress,
} from '../api-client';
import { checkPlaylist } from './twitch-recording-player/playlist';
import { ensureHlsLoaded, checkHlsSupport } from './twitch-recording-player/hls-loader';
import { initializePlayer, teardownPlayer } from './twitch-recording-player/hls-player';
import type { RecordingRuntimeState } from './twitch-recording-player/types';
import { fetchResumeProgress } from './twitch-recording-player/resume-manager';
import {
  preparePushProgress,
  shouldSkipSave,
  startProgressTracking,
  stopProgressTracking,
  updateAndSaveProgress,
} from './twitch-recording-player/progress-manager';

export const TwitchRecordingPlayerPage = (): ReactElement => {
  const { page } = useRouter();

  const [isInitialized, setIsInitialized] = useState(false);
  const [isLoading, setIsLoading] = useState(true);
  const [playbackError, setPlaybackError] = useState<string | null>(null);
  const [channelLogin, setChannelLogin] = useState('');
  const [filename, setFilename] = useState('');
  const playerElementRef = useRef<HTMLVideoElement | null>(null);
  const stateRef = useRef<RecordingRuntimeState>({
    channelLogin: '',
    filename: '',
    hlsInstance: null,
    isLoading: true,
    lastSavedPosition: 0,
    playbackError: null,
    playerEl: null,
    progressTimer: null,
    resumeSettled: false,
    resumeTargetPosition: null,
  });

  // Initialize params from URL
  useEffect(() => {
    const channelLoginParam = page.query.channel_login ?? '';
    const filenameParam = page.query.filename ?? '';
    setChannelLogin(channelLoginParam);
    setFilename(filenameParam);
    stateRef.current.channelLogin = channelLoginParam;
    stateRef.current.filename = filenameParam;
  }, [page.query.channel_login, page.query.filename]);

  const pushProgress = useCallback(async (force = false): Promise<void> => {
    const state = stateRef.current;
    const result = preparePushProgress(state);
    if (shouldSkipSave(result, state, force)) {
      return;
    }
    await updateAndSaveProgress(state, result, saveRecordingWatchProgress);
  }, []);

  const teardown = useCallback((): void => {
    void pushProgress(true);
    stopProgressTracking(stateRef.current);
    if (stateRef.current.hlsInstance !== null) {
      stateRef.current.hlsInstance.destroy();
    }
    stateRef.current.hlsInstance = null;
    teardownPlayer(stateRef.current);
  }, [pushProgress]);

  const initializePlayerFn = useCallback(async (): Promise<void> => {
    const state = stateRef.current;
    setPlaybackError(null);
    setIsLoading(true);
    state.isLoading = true;

    await fetchResumeProgress(state, getRecordingWatchProgress);

    const playlistResult = await checkPlaylist(state.channelLogin, state.filename);
    if (!playlistResult.exists) {
      setPlaybackError('HLS playlist not available for this recording.');
      setIsLoading(false);
      state.isLoading = false;
      return;
    }

    // Load hls.js if available, but don't block on failure - native fallback will handle it
    await ensureHlsLoaded();

    const hlsResult = checkHlsSupport();

    // Validate player element exists
    if (state.playerEl === null) {
      setPlaybackError('Failed to initialize video player.');
      setIsLoading(false);
      state.isLoading = false;
      return;
    }

    startProgressTracking(state, pushProgress);
    const initialized = initializePlayer({
      HlsClass: hlsResult.supported ? hlsResult.HlsClass : null,
      playlistUrl: playlistResult.url,
      setIsLoading,
      setPlaybackError,
      state,
    });
    if (!initialized) {
      setPlaybackError('HLS is not supported in this browser.');
      setIsLoading(false);
      state.isLoading = false;
    }
  }, [pushProgress]);

  // Initialize player when refs are ready
  useEffect(() => {
    if (
      playerElementRef.current === null ||
      channelLogin === '' ||
      filename === '' ||
      isInitialized
    ) {
      return;
    }

    setIsInitialized(true);
    stateRef.current.playerEl = playerElementRef.current;
    void initializePlayerFn();
  }, [channelLogin, filename, isInitialized, initializePlayerFn]);

  // Cleanup on unmount
  useEffect((): (() => void) => (): void => {
    teardown();
  }, [teardown]);

  const goBack = useCallback((): void => {
    navigate('/twitch/recordings');
  }, []);

  return (
    <section className="ui-page-panel ui-page-panel--wide">
      <header className="ui-page-header">
        <div>
          <p className="ui-page-eyebrow">Recording Playback</p>
          <h1 className="ui-page-title">{channelLogin || 'unknown channel'}</h1>
          {filename && (
            <p className="ui-page-subtle" title={filename}>
              {filename}
            </p>
          )}
        </div>
        <button type="button" className="ui-nav-chip" onClick={goBack}>
          Back to recordings
        </button>
      </header>

      {!channelLogin || !filename ? (
        <p className="ui-error">Missing recording playback parameters.</p>
      ) : (
        <>
          <div className="player-wrapper">
            {isLoading && (
              <div className="player loading">
                <p className="ui-muted">Loading player...</p>
              </div>
            )}
            <video
              ref={playerElementRef}
              className={`player ${isLoading ? 'hidden' : ''}`}
              controls
              preload="auto"
            >
              Your browser cannot play this recording format.
            </video>
          </div>
          {playbackError !== null && playbackError !== '' && (
            <p className="ui-error" role="alert">
              {playbackError}
            </p>
          )}
        </>
      )}
    </section>
  );
};
