// web/src/lib/pages/you-tube-home-page.svelte
<script lang="ts">
  import { onMount } from 'svelte';

  import { navigate } from '$lib/router/router.svelte';
  import { type YoutubeChannel, getYouTubeSubscriptions } from '$lib/api-client';
  import { EmptyState, ErrorState, SkeletonMediaList } from '$lib/components/ui';
  import { LoadedFade, YouTubeMediaRow, YouTubeShell } from '$lib/components/youtube';

  const FAILED_TO_LOAD = 'Failed to load subscriptions';
  const LIST_ITEM_COUNT = 8;
  const NO_SUBS_DESC = 'Subscribe to YouTube channels in Invidious to see them here.';
  const NO_SUBS_TITLE = 'No subscriptions found';

  const INITIAL_SLICE_INDEX = 0;
  const INITIAL_SLICE_LENGTH = 1;

  let channels = $state<readonly YoutubeChannel[]>([]);
  let isLoading = $state(true);
  let error = $state<string | null>(null);

  const loadSubscriptions = async (): Promise<void> => {
    isLoading = true;
    error = null;
    try {
      channels = await getYouTubeSubscriptions();
    } catch (error_) {
      const errorMessage = error_ instanceof Error ? error_.message : FAILED_TO_LOAD;
      error = errorMessage;
    } finally {
      isLoading = false;
    }
  };

  onMount(loadSubscriptions);

  const openChannel = (channelId: string): void => {
    navigate(`/youtube/channel/${encodeURIComponent(channelId)}`);
  };
</script>

<YouTubeShell activeTab="subscriptions">
  {#if isLoading}
    <SkeletonMediaList count={LIST_ITEM_COUNT} />
  {:else if error}
    <ErrorState
      message={error}
      onRetry={loadSubscriptions}
      isRetrying={isLoading}
    />
  {:else if channels.length === 0}
    <EmptyState
      title={NO_SUBS_TITLE}
      description={NO_SUBS_DESC}
      variant="channels"
    />
  {:else}
    <LoadedFade loaded={true}>
      <div class="ui-list">
        {#each channels as channel (channel.channel_id)}
          {#snippet visual()}
            {#if channel.avatar}
              <img
                class="ui-avatar channel-avatar"
                src={channel.avatar}
                alt={channel.name}
                loading="lazy"
              />
            {:else}
              <div class="ui-avatar ui-avatar-fallback channel-avatar fallback">
                {channel.name.slice(INITIAL_SLICE_INDEX, INITIAL_SLICE_LENGTH)}
              </div>
            {/if}
          {/snippet}

          {#snippet meta()}
            {#if channel.description}
              <span class="ui-media-meta channel-description" title={channel.description}>{channel.description}</span>
            {/if}
          {/snippet}

          {@const metaSnippet = channel.description ? meta : undefined}
          <YouTubeMediaRow
            title={channel.name}
            onClick={() => openChannel(channel.channel_id)}
            {visual}
            meta={metaSnippet}
            extraClass="youtube-channel-row"
          />
        {/each}
      </div>
    </LoadedFade>
  {/if}
</YouTubeShell>

<style>
  .channel-avatar {
    width: 74px;
    height: 74px;
    border-radius: 50%;
    font-size: 1.35rem;
  }

  .channel-description {
    line-height: 1.4;
    display: -webkit-box;
    line-clamp: 3;
    -webkit-line-clamp: 3;
    -webkit-box-orient: vertical;
    overflow: hidden;
    text-overflow: ellipsis;
    white-space: pre-line;
  }

  :global(.youtube-channel-row) {
    display: grid;
    grid-template-columns: 74px minmax(0, 1fr);
    align-items: center;
    gap: 0.75rem;
    padding: 0.8rem;
    text-align: left;
  }
</style>

// web/src/pages/YouTubeHomePage.tsx
import { useCallback, useEffect, useState } from 'react';
import type { ReactElement } from 'react';
import {
  SkeletonMediaList,
  ErrorState,
  EmptyState,
  LoadedFade,
  MediaRow,
  MediaRowMeta,
} from '../components/ui';
import { YouTubeShell } from '../components/youtube';
import { getYouTubeSubscriptions, type YoutubeChannel } from '../lib/api-client';
import { navigate } from '../router';

const FAILED_TO_LOAD = 'Failed to load subscriptions';
const LIST_ITEM_COUNT = 8;
const NO_SUBS_DESC = 'Subscribe to YouTube channels in Invidious to see them here.';
const NO_SUBS_TITLE = 'No subscriptions found';
const INITIAL_SLICE_INDEX = 0;
const INITIAL_SLICE_LENGTH = 1;

export function YouTubeHomePage(): ReactElement {
  const [channels, setChannels] = useState<readonly YoutubeChannel[]>([]);
  const [isLoading, setIsLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);

  const loadSubscriptions = useCallback(async (): Promise<void> => {
    setIsLoading(true);
    setError(null);
    try {
      const data = await getYouTubeSubscriptions();
      setChannels(data);
    } catch (error_) {
      const errorMessage = error_ instanceof Error ? error_.message : FAILED_TO_LOAD;
      setError(errorMessage);
    } finally {
      setIsLoading(false);
    }
  }, []);

  useEffect(() => {
    void loadSubscriptions();
  }, [loadSubscriptions]);

  const openChannel = useCallback((channelId: string): void => {
    navigate(`/youtube/channel/${encodeURIComponent(channelId)}`);
  }, []);

  return (
    <YouTubeShell activeTab="subscriptions">
      {isLoading ? (
        <SkeletonMediaList count={LIST_ITEM_COUNT} />
      ) : error !== null && error !== '' ? (
        <ErrorState message={error} onRetry={loadSubscriptions} isRetrying={isLoading} />
      ) : channels.length === 0 ? (
        <EmptyState title={NO_SUBS_TITLE} description={NO_SUBS_DESC} variant="channels" />
      ) : (
        <LoadedFade loaded={true}>
          <div className="ui-list">
            {channels.map((channel) => (
              <MediaRow
                key={channel.channel_id}
                title={channel.name}
                onClick={() => {
                  openChannel(channel.channel_id);
                }}
                extraClass="youtube-channel-row"
                visual={
                  channel.avatar !== undefined && channel.avatar !== '' ? (
                    <img
                      className="ui-avatar channel-avatar"
                      src={channel.avatar}
                      alt={channel.name}
                      loading="lazy"
                    />
                  ) : (
                    <div className="ui-avatar ui-avatar-fallback channel-avatar fallback">
                      {channel.name.slice(INITIAL_SLICE_INDEX, INITIAL_SLICE_LENGTH)}
                    </div>
                  )
                }
                meta={
                  channel.description !== undefined && channel.description !== '' ? (
                    <MediaRowMeta>
                      <span
                        className="ui-media-meta channel-description"
                        title={channel.description}
                      >
                        {channel.description}
                      </span>
                    </MediaRowMeta>
                  ) : undefined
                }
              />
            ))}
          </div>
        </LoadedFade>
      )}
    </YouTubeShell>
  );
}
