// web/src/components/layout/app-version.tsx
import { useEffect, useState, type ReactElement } from 'react';
import { getVersion } from '../../api-client/version';

const UNKNOWN_VERSION = '…';
const ERROR_VERSION = '?';

export default function AppVersion(): ReactElement {
  const [version, setVersion] = useState(UNKNOWN_VERSION);

  useEffect(() => {
    const fetchVersion = async (): Promise<void> => {
      try {
        const { version: ver } = await getVersion();
        setVersion(ver);
      } catch {
        setVersion(ERROR_VERSION);
      }
    };

    fetchVersion().catch(() => {
      setVersion(ERROR_VERSION);
    });
  }, []);

  return (
    <p className="app-version" aria-label="App version">
      via Twitch Relay · v{version}
    </p>
  );
}

// web/src/lib/components/app-version.svelte
<script lang="ts">
  import { getVersion } from '$lib/api-client';
  import { onMount } from 'svelte';

  const UNKNOWN_VERSION = '…';
  const ERROR_VERSION = '?';

  let version = $state(UNKNOWN_VERSION);

  onMount(async () => {
    try {
      const { version: ver } = await getVersion();
      version = ver;
    } catch {
      version = ERROR_VERSION;
    }
  });
</script>

<p class="app-version" aria-label="App version">v{version}</p>

<style>
  .app-version {
    margin-top: 2rem;
    padding: 0.75rem 0 0;
    text-align: center;
    font-size: 0.72rem;
    letter-spacing: 0.06em;
    color: var(--muted);
    user-select: none;
  }
</style>
